### PR TITLE
Fixed bug where loadqueue wasn't always getting processed.

### PR DESCRIPTION
**Pull request by bdlangton**

### CODE REVIEW

**Comment by travist** [comment]
The only issue I see with this is that loadAll is not a synchronous function, so the selectChildren will get called before the tree is finished loading.  Is this going to be an issue?

**Comment by bdlangton** [comment]
I will need to investigate further. It seemed to work fine in testing, but I'll have to see if there are any potential problems.

**Comment by bdlangton** [comment]
Updated my solution to the problem.

**Comment by travist** [comment]
:+1:

**Pull request merged**
